AllCops:
  SuggestExtensions: false
  EnabledByDefault: true

Style/IfUnlessModifier:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false